package utils

//Estrutura usada
type MensagemErroMap struct {
	Codigo     int
	Mensagem   string
	Ocorrencia string
}

var MensagemErro = []MensagemErroMap{
	{51000, "Erro inesperado de banco de dados: [Causa do erro].", "Erros ocorridos no banco de dados, como tabela ou campo não encontrado, conversão de tipos ou outros erros não previstos da aplicação."},
	{51002, "Campo obrigatório não informado: [Campo obrigatório]", "Algum campo obrigatório não foi informado na chamada do serviço."},
	{51003, "Codigo não encontrado:[Código específico]", "Foi informado um código para um domínio ou tipo de registro específico que não foi encontrado entre os cadastros do sistema (Ex: cód. Banco, conta header, cód. espécie de título)."},
	{51004, "Número de carteira informado não autorizado a operar nesse canal.", "Foi informado um número de carteira não autorizado a operar nesse canal."},
	{51005, "Código de modalidade informado não autorizado a operar nesse canal.", "Foi informado um código de modalidade não autorizado a operar nesse canal."},
	{51006, "O banco correspondente informado não atende a modalidade selecionada.", "Foi informada uma modalidade não atendida pelo banco cobrador indicado."},
	{51007, "Não podem ser informados código de modalidade de banco e um código de banco correspondente para uma carteira de cobrança própria.", "Foi informada uma carteira de cobrança própria e ao mesmo tempo indicado um código de banco diferente do nosso ou uma modalidade de cobrança em correspondente (Carteiras 100, 101, 121, 108, 110 e 180)."},
	{51008, "Modalidade informada deve ser atendida por bancos correspondentes.", "Foi informada uma modalidade de cobrança em banco correspondente para uma carteira de cobrança própria. (Carteiras 112 ou 144 e modalidades 101, 104, 108, 109, 110, 111, 112, 115, 121, 180, 181, 210, 215 ou 218)."},
	{51009, "Título na modalidade informada deve ser obrigatoriamente da carteira 112 ou 144.", "Foi informada uma modalidade que obrigatoriamente deveria ser atendida pelas carteiras 112 ou 144, mas foi indicado um número de carteira diferente. (Modalidades 101, 104, 108, 109, 110, 111, 112, 115, 121, 180, 181, 210, 215, 218)."},
	{51010, "Não são aceitas inclusões de cheque (código de espécie \"01\").", "Foi informado um código de espécie de documento de cheque. Não são aceitas inclusões de cheques por esse canal."},
	{51011, "Esse canal não aceita produtos diferentes de cobrança de terceiros.", "O código de produto da operação da conta header informada pertence a uma classe diferente de cobrança de terceiros. Apenas esse tipo de cobrança será aceito nesse canal."},
	{51012, "Código de cliente informado não corresponde ao titular da conta header.", "O cliente associado à conta header informada não é o mesmo informado como parâmetro de entrada nesse serviço."},
	{51013, "Ocorreu um erro na verificação de situação do beneficiário: Situação: [Código de Situação 000 ou 001]", "Ao executar a consulta da situação de beneficiário do título ocorreu um erro inesperado."},
	{51014, "Realizando checagem de situação cadastral. Favor tentar novamente mais tarde. (Situação = [Código de Situação 021 ou 022])", "Sistema está aguardando o retorno e o processamento de uma consulta da situação do beneficiário do título na CIP."},
	{51015, "Situação do beneficiário não permite a realização da operação. (SITUACAO = [Código de Situação 005 ou 006])", "A situação atual apurada do beneficiário do título não permite a realização da entrada do título."},
	{51017, "Informar um conteúdo maior que zero para o campo: [Campo Numérico]", "Foi informado um valor numérico igual ou menor que zero para um campo que não aceita essa condição."},
	{51018, "Informar um conteúdo maior ou igual a zero para o campo: [Campo Numérico]", "Foi informado um valor menor que zero para um campo numérico que não aceita essa condição."},
	{51019, "Valor de abatimento deve ser menor que valor nominal do título.", "O valor de abatimento informado é maior que o valor nominal do título."},
	{51020, "Informar \"sim\" ou \"não\" para aceite do título.", "Foi informado um valor diferente dos domínios aceitos para o campo de aceite do título."},
	{51021, "Data de vencimento informada não e dia útil.", "Foi apurado pelo sistema que a data informada para vencimento do título não é um dia útil."},
	{51022, "O título deve ter data de vencimento maior que a data atual.", "A data de vencimento informada para o título é menor que a data do sistema."},
	{51024, "Informar tipo pessoa do pagador \"1\" para pessoa física e tipo pessoa \"2\" para pessoa jurídica.", "Foi informado um valor diferente dos domínios aceitos para o campo de tipo pessoa do pagador do título."},
	{51025, "CPF / CNPJ do pagador inválido.", "Foi informado um CPF ou CNPJ inválido do pagador do título."},
	{51026, "Nosso número não deve ser informado para a carteira selecionada.", "Caso de quando a cobrança será feita na carteira 112 ou 144, o nosso número será gerado pelo sistema e não deve ser informado."},
	{51027, "Não foi encontrado banco cobrador para a operação.", "Durante a execução da rotina que determina o banco cobrador, não foi encontrado nenhum banco que fosse habilitado a realizar a cobrança do título (seja no nosso banco ou correspondente)."},
	{51028, "Nosso número deve ser informado para a carteira selecionada.", "Caso de quando a cobrança será feita na carteira 108, 180 ou 110, o nosso número não será gerado pelo sistema e deve ser informado."},
	{51029, "Cobrança não coberta pelo nosso banco.", "Após execução da rotina que determina o banco cobrador, foi verificado que o nosso banco não se habilita num cenário de cobrança própria."},
	{51030, "Numeração de título já utilizada no sistema.", "O nosso número informado como entrada do serviço já foi utilizado por um título no sistema."},
	{51031, "Numeração de nosso número informada está fora das faixas cedidas ao beneficiário.", "O nosso número informado não está inserido entre as faixas de número cedidas ao beneficiário no sistema."},
	{51032, "DígitoVerificador do nosso número informado invalido.", "O DígitoVerificador do nosso número informado foi dado como inválido após realização do cálculo."},
	{51033, "Nosso número bancos não foi informado.", "Caso das modalidades 101, 108, 109, 115, 121 e 180, o nosso número bancos não será gerado pelo sistema e deve ser informado como entrada do serviço."},
	{51034, "Não são permitidas cobranças para pagadores eletrônicos para a modalidade selecionada.", "Caso das modalidades 101, 108, 109, 115, 121, 180, 110, 111, 181, 210, 215 ou 218, o pagador não pode ser eletrônico, senão o título não pode ser emitido por esse serviço."},
	{51035, "Nenhuma faixa registrada para atender o nosso número bancos informado.", "O nosso número bancos informado não está inserido entre as faixas de número cedidas ao beneficiário no sistema."},
	{51036, "Não existe numeração disponível para o banco e carteira: [Cód. Banco / Carteira]", "Na tentativa de gerar o nosso número bancos, não foi encontrada nenhuma numeração disponível para o título."},
	{51037, "O banco correspondente informado não cobra o CEP do pagador.", "Após executar a rotina que determina o banco cobrador para o título, foi verificado que o banco cobrador informado como entrada do serviço não atende o CEP do pagador."},
	{51039, "Deve ser informada data para o código utilizado: [Desconto X ou Mora]", "Para o código de desconto ou mora selecionado, deve ser informada data."},
	{51040, "A data informada deve ser menor ou igual ao vencimento: [“Data de Desconto X”]", "A data em questão deve ser menor ou igual ao vencimento."},
	{51041, "Não deve ser informada data para o código utilizado: [Desconto X ou Mora]", "Para o código de desconto ou mora selecionado, não deve ser informada data."},
	{51042, "Deve ser informado um valor para o código utilizado: [Desconto X, Código de Mora ou Multa]", "O código de desconto, mora ou multa selecionado exige que seja informado um valor."},
	{51043, "A taxa deve ser zero para o código informado: [Desconto, Mora ou Multa]", "Para o código de desconto, mora ou multa selecionado, a taxa percentual deve vir zerada."},
	{51044, "Deve ser informada uma taxa para o código utilizado: [Desconto X, Código de Mora ou Multa]", "Deve ser informada uma taxa para o código utilizado: [Desconto X, Código de Mora ou Multa]"},
	{51045, "O valor deve ser zero para o código informado: [Desconto X, Mora ou Multa]", "Para o código de desconto, mora ou multa selecionado, o valor deve vir zerado."},
	{51046, "Os códigos de desconto que forem informados devem ser do mesmo tipo.", "Quando informado um determinado código de desconto, todos os demais que venham a ser preenchidos devem ser do mesmo tipo."},
	{51047, "A data informada deve ser maior que a data de vencimento: [Mora ou Multa]", "A data de mora ou multa informada é menor que a data de vencimento."},
	{51048, "Informar \"sim\" ou \"não\" se título possui agenda.", "Deve ser informado “SIM” ou “NÃO” no campo que diz se o título possui agenda."},
	{51049, "Informar tipo de agenda.", "Foi informado que título teria agendamento de cartório, mas não foi informado que tipo de agenda seria."},
	{51050, "Informar tipo de agenda \"d\" para devolução ou \"c\" para cartório.", "São considerados domínios válidos para o tipo de agenda do título C para cartório e D para devolução."},
	{51051, "Informar número de dias de agenda maior que zero.", "O número dias de agendamento de cartório após o vencimento deve ser um valor maior que zero."},
	{51052, "Informar critério para dias de agenda.", "O campo de critério para dias de agenda deve ser informado se o título possui agenda."},
	{51053, "Informar critério dias de agenda \"1\" para dias corridos ou \"2\" para dias uteis.", "O domínio aceito para o critério de dias de agendamento deve ser 1 para contagem em dias corridos ou 2 para dias úteis."},
	{51054, "Informar tipo pessoa sacador \"1\" para sacador pessoa física ou \"2\" para sacador pessoa jurídica.", "Os domínios aceitos para tipo pessoa sacador são 1 para pessoa física ou 2 para pessoa jurídica."},
	{51055, "Não existe numeração em agencia_carteiras para a agencia e carteira: [Código da Agência do Título / Número da Carteira do Título]", "Ao realizar a rotina de geração de nosso número, não foi encontrada faixa de numeração para a agência e carteira do título sendo incluído."},
	{51056, "Produto destino do título não aceita pagamentos parciais.", "O header informado levou a uma operação de produto que não aceita títulos de pagamentos parciais."},
	{51062, "A data informada e inválida: [Nome do Campo]", "Foi apurado que o campo especificado não está no formato correto de data: (DD/MM/AAAA)."},
	{51064, "A data de emissão deve ser menor ou igual à data do sistema de cobrança.", "Data de emissão informada está inconsistente com a data do Sistema de Cobrança."},
	{51065, "Código de cliente informado não está cadastra do no infobank.", "Código de cliente informado não está cadastrado no infobank."},
	{51066, "Cobrança interna do banco não pode usar este canal.", "Sistemas legados internos do banco não podem usar este serviço para inclusão de títulos."},
	{51067, "Um campo ultrapassou o tamanho máximo de caracteres: [tamanho do campo].", "O conteúdo informado excede o tamanho máximo permitido para este campo."},
	{51069, "CNPJ/CPF do sacador inválido.", "CNPJ/CPF do sacador inconsistente."},
	{51070, "Informar endereço completo do sacador.", "Os dados completos do endereço do sacador são obrigatórios e não foram informados."},
	{51071, "Espécie de documento 31 só permitido para moeda real.", "Espécie de documento informada igual a 31 e moeda informada não é REAL."},
	{51106, "Conta informada para creditar não encontrada.", "Foi informada a conta para ser creditada que não foi localizada nos cadastros de contas."},
	{51107, "Produto associado a operação não aceita desvio de crédito.", "O produto que está associado a operação informada (conta header) não aceita desvio de crédito. Só ocorrerá esse erro se as informações de conta a creditar estiver no request."},
}
